#!/usr/bin/python3
import logging
import sys
import os
import trio

sys.argv[0:1] = [sys.argv[0], "-c","mapper.cfg"]
sys.path[0:0] = ["../trio","../alembic","../sqlalchemy/lib"]

from mudpyc.mapper.main import main
try:
	main()
except trio.Cancelled as exc:
	import pdb;pdb.set_trace()
	raise

